package rs.ac.bg.fon.ai.forme;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JTable;

import rs.ac.bg.fon.ai.domen.Trener;
import rs.ac.bg.fon.ai.domen.Trening;
import rs.ac.bg.fon.ai.komunikacija.KomunikacijaSaServerom;
import rs.ac.bg.fon.ai.model.ModelTabeleTreniranje;
import rs.ac.bg.fon.ai.transkript.KlijentskiZahtev;
import rs.ac.bg.fon.ai.transkript.Operacije;
import rs.ac.bg.fon.ai.transkript.ServerskiOdgovor;

public class FrmKlijent extends javax.swing.JFrame {
Trener ulogovan;
    /**
     * Creates new form FrmKlijent
     */
    public FrmKlijent() {
        initComponents();
    }

    FrmKlijent(Trener korisnik) {
           initComponents();
ulogovan= korisnik;
prepareTable();
        setLocationRelativeTo(null);

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrening = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        btnNapraviTr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTrening.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTrening);

        btnDodaj.setText("Dodaj polaznika u bazu");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnNapraviTr.setText("Napravi trening");
        btnNapraviTr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNapraviTrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSacuvaj)
                            .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNapraviTr, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnDodaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNapraviTr)
                .addGap(31, 31, 31)
                .addComponent(btnSacuvaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {                                         
 
  new FrmDodaj(this, true,ulogovan).setVisible(true);        

// TODO add your handling code here:
    }                                        

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {                                           
ModelTabeleTreniranje mt= (ModelTabeleTreniranje) tblTrening.getModel();
List<Trening> list= mt.getListaPP();
        System.out.println("ovo je lista za cuvanje:\n");
        System.out.println(list);
if(list!=null && list.size()>0){
    KlijentskiZahtev kz= new KlijentskiZahtev(Operacije.SACUVAJ_TRENINGE, list);
    KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
    ServerskiOdgovor so= KomunikacijaSaServerom.getInstance().primiOdgovor();
    
    if(so.isUspesno()){
        JOptionPane.showMessageDialog(this, "uspesno je sacuvana");
    }
    else         JOptionPane.showMessageDialog(this, "  nije sacuvana");

}
   
        
// TODO add your handling code here:
    }                                          

    private void btnNapraviTrActionPerformed(java.awt.event.ActionEvent evt) {                                             

  new FrmNapraviTrening(this, true,ulogovan).setVisible(true);        

        // TODO add your handling code here:
    }                                            

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnNapraviTr;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTrening;
    // End of variables declaration                   

    private void prepareTable() {
   
        ModelTabeleTreniranje mt= new ModelTabeleTreniranje();
        tblTrening.setModel(mt);
    
    }

    public JTable getTblTrening() {
        return tblTrening;
    }
    
}
