package rs.ac.bg.fon.ai.forme;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

import rs.ac.bg.fon.ai.domen.Trener;
import rs.ac.bg.fon.ai.komunikacija.KomunikacijaSaServerom;
import rs.ac.bg.fon.ai.transkript.KlijentskiZahtev;
import rs.ac.bg.fon.ai.transkript.Operacije;
import rs.ac.bg.fon.ai.transkript.ServerskiOdgovor;

public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
                setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        txtKorIme = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSifra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogin.setText("Uloguj se");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel1.setText("Korisnicko ime");

        jLabel2.setText("Sifra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKorIme)
                    .addComponent(txtSifra, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKorIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>                        

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String korIme = txtKorIme.getText().trim();
        String pass = txtSifra.getText();
        System.out.println(korIme);
        System.out.println(pass);
Trener t= new Trener();
t.setKorisnickoIme(korIme);
t.setSifra(pass);
        if (korIme.isEmpty() || pass.isEmpty())
        JOptionPane.showMessageDialog(this, "Niste uneli neko polje");

        List<Trener> listK = new ArrayList<>();

        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_TRENERE);

        KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);

        ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().primiOdgovor();
        listK = (List<Trener>) so.getOdgovor();

        if (listK == null || listK.size() == 0) {
            System.out.println("lista trenera je prazna, nije moguce ulogovati se");
        }
        int brojac = 0;
        for (Trener korisnik : listK) {
            if (korisnik.getKorisnickoIme().equals(korIme) && korisnik.getSifra().equals(pass)) {
                brojac++;
                new FrmKlijent(korisnik).setVisible(true);
                this.dispose();
            }

        }
        if (brojac == 0) {
            JOptionPane.showMessageDialog(this, "Logovanje nije uspelo");
        }

        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtKorIme;
    private javax.swing.JPasswordField txtSifra;
    // End of variables declaration                   
}

